### PR TITLE
Add effects + some refactoring

### PR DESCRIPTION
**Pull request by hacker-h**
This PR refactors a lot of the code and implements a pattern for effects which consists of spawning a process that maintains an effect. The advantage of this pattern is, that effects can be changed and cleaned up with almost no latency.
Due to severe performance issues the used python library had to be switched.
Three effects have been added/implemented: Theater Rainbow, Rainbow, Knight Rider

The Dockerfile has been refactored to enhance caching on builds and reduce the final image size.
Currently the strandtest.py is checked into code, it could also be included into the dockerfile using 
`ADD https://github.com/rpi-ws281x/rpi-ws281x-python/blob/v4.2.4/examples/strandtest.py /app/strandtest.py`

An example docker-compose file was also added.

I did a lot of changes, so feel free to adapt this PR's code to your needs.

### CODE REVIEW

**Comment by pilotak** [comment]
good job!

Here are a few things:
- when turned on in HASS nothing brights up until you select a "knight rider" (which can now be renamed to "None"?)  i don't think this is an ideal - it should either remember last effect selected or use default none
- multi-stage dockerfile - the purge commands is no longer needed?
- dockerfile update bellow

```dockerfile
# Builder
FROM python:3.8-slim as builder

COPY ./requirements.txt ./

RUN apt update \
    && apt install -y --no-install-recommends gcc make build-essential scons swig \
    && pip3 install --user -r requirements.txt

# Executor
FROM python:3.8-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY ./strandtest.py ./ws281x.py ./

CMD ["python", "-u", "./ws281x.py"]
```
- could please rename `strandtest.py` to `effects.py` - so it makes more sense
- i would actually remove `docker-compose.yml` and we can put mosquitto bit to readme
- there is no need for `volume` in docker-compose

**Comment by hacker-h** [comment]
will refactor this a bit

**Comment by pilotak** [comment]
@hacker-h please wait with more updates, I will push a lot of changes tomorrow

**Comment by pilotak** [comment]
I have tested it and it works like a charm. You can of course further improve the code

**Comment by hacker-h** [comment]
I like it! feel free to merge

**Pull request merged**
